version: '3'
services:
  app:
    image: 'php:8.2-fpm'
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    networks:
      - laravel
  web:
    image: 'nginx:latest'
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel
  mysql:
    image: 'mysql:8.0'
    environment:
      MYSQL_DATABASE: molpi
      MYSQL_ROOT_PASSWORD: root
    networks:
      - laravel
  redis:
    image: 'redis:latest'
    networks:
      - laravel
  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    networks:
      - laravel
networks:
  laravel: